<?php
/**
 * @file
 * Content import using migrate from Google Spreadsheet/JSON
 */

/**
 * Allow other modules to define migrations using ts_content.

 * @return array
 *   Array of migration information. Can be looped through and used in a
 *   hook_migrate_api() implementation.
 */
function ts_content_get_info() {
  $ts_content_info = module_invoke_all('ts_content_info');

  foreach ($ts_content_info as $name => $data) {
    $ts_content_info[$name] += array(
      'class' => NULL,
      'type' => NULL,
      'data_url' => NULL,
      'fields' => array(),
    );
  }

  return $ts_content_info;
}

/**
 * Helper to convert date into migrate friendly format.
 */
function ts_content_date_convert($date) {
  // Puts dates into YYYY-MM-DD format.
  return format_date(strtotime($date), 'custom', 'Y-m-d');
}

/**
 * Helper to convert y/n values for Author -> expert field into boolean.
 */
function ts_content_boolean_convert($bool) {
  // Puts Y/N && yes/no, into 1/0 format.
  $bool = strtolower(substr($bool, 0, 1));
  switch ($bool) {
    case 'y':
      return 1;

    case 'n':
      return 0;
  }
}
